name: urban-access
channels:
  - conda-forge
dependencies:
  - python=3.12
  - geopandas
  - osmnx
  - scikit-learn
  - networkx
  - matplotlib
  - pandas
  - shapely
  - folium
  - tqdm
  - jupyter
  - ipywidgets
